/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Model.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} position={[0, 0.05, 0]} scale={[3, -0.41, 3]} />
      <group position={[0, 0.68, 0]} scale={[3.19, -0.3, 3.19]}>
        <mesh geometry={nodes.Cube001_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials['Material.001']} />
      </group>
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.002']} position={[-0.03, 0.87, 0]} scale={[3.25, 1, 0.79]} />
      <group position={[2.24, 1.05, -2.54]} scale={0.1}>
        <mesh geometry={nodes.Cube003_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube003_2.geometry} material={materials['Material.004']} />
      </group>
      <group position={[1.87, 1.02, -1.48]} scale={0.07}>
        <mesh geometry={nodes.Cube004_1.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube004_2.geometry} material={materials['Material.006']} />
      </group>
      <group position={[1.22, 1.08, -2.32]} rotation={[0, -0.28, 0]} scale={0.07}>
        <mesh geometry={nodes.Cube005_1.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube005_2.geometry} material={materials['Material.006']} />
      </group>
      <group position={[-1.87, 0.99, -1.76]} rotation={[0, -0.02, 0]} scale={0.06}>
        <mesh geometry={nodes.Cube006_1.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials['Material.006']} />
      </group>
      <group position={[-3.05, 1.15, -2.44]} rotation={[0, -0.28, 0]} scale={0.09}>
        <mesh geometry={nodes.Cube007_1.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube007_2.geometry} material={materials['Material.006']} />
      </group>
      <group position={[-1.37, 1.03, 1.29]} rotation={[0, -0.28, 0]} scale={0.08}>
        <mesh geometry={nodes.Cube008_1.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube008_2.geometry} material={materials['Material.006']} />
      </group>
      <group position={[-0.61, 1.02, -2.29]} rotation={[0, 0.28, 0]} scale={0.13}>
        <mesh geometry={nodes.Cube009_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube009_2.geometry} material={materials['Material.004']} />
      </group>
      <group position={[0.26, 1.06, -1.3]} scale={0.07}>
        <mesh geometry={nodes.Cube010_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube010_2.geometry} material={materials['Material.004']} />
      </group>
      <group position={[0.55, 1.17, 1.66]} rotation={[0, 0.24, 0]} scale={0.12}>
        <mesh geometry={nodes.Cube011_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube011_2.geometry} material={materials['Material.004']} />
      </group>
      <group position={[2.59, 2.14, 2.21]} rotation={[-Math.PI, -0.55, -Math.PI]} scale={0.42}>
        <mesh geometry={nodes.Icosphere001_1.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Icosphere001_2.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Icosphere001_3.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Icosphere001_4.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Icosphere001_5.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Icosphere001_6.geometry} material={materials['Material.012']} />
      </group>
      <group position={[-3.17, 2.44, 2.3]} rotation={[0, 0.66, 0]} scale={0.54}>
        <mesh geometry={nodes.Icosphere005.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Icosphere005_1.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Icosphere005_2.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Icosphere005_3.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Icosphere005_4.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Icosphere005_5.geometry} material={materials['Material.012']} />
      </group>
      <mesh geometry={nodes.Icosphere.geometry} material={materials['Material.013']} position={[-1.97, 0.85, 0.03]} scale={-0.17} />
      <mesh geometry={nodes.Icosphere003.geometry} material={materials['Material.013']} position={[-0.23, 0.79, -0.36]} scale={-0.17} />
      <mesh geometry={nodes.Icosphere004.geometry} material={materials['Material.013']} position={[1.94, 0.79, -0.15]} scale={-0.17} />
      <mesh geometry={nodes.react.geometry} material={materials.react} position={[0.2, 3.83, -0.03]} rotation={[Math.PI / 2, 0, -0.82]} scale={2.36} />
    </group>
  )
}

useGLTF.preload('/Model.glb')
